#!/bin/sh
# prerm script for dovecot-fetchmail

set -e

if [ -d /run/systemd/system ]; then
	deb-systemd-invoke restart dovecot || :
else
	if [ -x "/etc/init.d/dovecot" ]; then
		if [ -x /usr/sbin/invoke-rc.d ]; then
			invoke-rc.d dovecot start
		else
			/etc/init.d/dovecot start
		fi
	fi
fi

#DEBHELPER#
